[package]
name = "git_push"
version = "0.1.0"
edition = "2024"
description = "Client to push git repositories over HTTP"

[dependencies]
base64 = { path = "../base64" }
cast = { path = "../cast" }
error = { path = "../error" }
hexadecimal = { path = "../hexadecimal" }
http = { path = "../http" }
sha = { path = "../sha" }
