[package]
name = "trade_server"
version = "0.1.0"
edition = "2024"
description = "Trading server"

[dependencies]
cast = { path = "../cast" }
connection = { path = "../connection" }
decimal = { path = "../decimal" }
error = { path = "../error" }
future = { path = "../future" }
log = { path = "../log" }
protobuf = { path = "../protobuf" }
time = { path = "../time" }
