[package]
name = "trade_ui"
version = "0.1.0"
edition = "2024"
description = "UI to monitor live trading"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
cast = { path = "../cast" }
error = { path = "../error" }
platform = { path = "../platform" }
time = { path = "../time" }
trade_clip = { path = "../trade_clip" }
